### ISSUE TITLE
considering using vue.js/vuex to enable live reload without losing state

### ISSUE THREAD

**Issue by delaneyj** [jscad/jscad-desktop#21]
Currently if you make underlying changes to components the params UI gets reset to its defaults every time making it hard to see minor changes without a bunch of setup.  Would it help to give of prototype of how to set that up?  Not sure if there are any special considerations for electron.  Has added benefits of time traveling debugger, state and async flow management via chrome extensions.

**Comment by kaosat-dev** [comment]
@delaneyj  by components / changes to you mean to a jscad design or the app code ?
If it is for the design then that is a bug with the way the parameters are displayed on screen which need to be fixed :) 
Can you elaborate a bit more on live reload/ etc if I am missing the point above ?
Would love to collaborate ! 

As for Vue: really sorry honestly I had to use for the past few months professionally ....and I really really dislike it... Over engineered, no clear data flow etc (and I am using mild words haha :D

**Comment by delaneyj** [comment]
Not sure where the bug is but if you change a function that generates CAG objects your parameters get set back to the default values.

Interesting, I have used React, Angular 1 & 2 and Vue 2.x makes by far the most sense to me.  Did you use it in conjuction with vuex, the router and [the debugger](https://github.com/vuejs/vue-devtools)?  Basically you can see how all actions flow though the state tree, go back in time etc.  When you make changes to components the state is not effected.  I build casino system dashboards with it and feel like I can see the flow better than anything I've seen for any GUI dev.

To each there own but the behavior of losing current state (including camera position) remains.  If it helps we can to a discord or hangout.

**Comment by kaosat-dev** [comment]
Ok I added an issue to track the param issues https://github.com/jscad/jscad-desktop/issues/25

I really liked React, and a lot of its children Preact,  Cycle.js etc But Vue , much like Angular did not stick with me , I did not like the useless templating, the eventing etc , well , anything really haha :)
I guess a lot of it boils down to taste :) 
Cycle.js & co still remain my favorites because I am very partial to observables , and in the end it remains very close to basic function composition ie view(state(actions)).

I know where the specific problem of partially resetting state comes from: I was trying to 'recycle' /reuse too much of the previous state. Also , is very likely related to me re-using some 'older' OpenJSCAD code to generate the input fields that does not always play well with the `morphdom`/ vdom approach https://github.com/jscad/jscad-desktop/blob/master/src/ui/main.js#L11

**Comment by kaosat-dev** [comment]
About hangouts: that would be great ! (as long as we do not speak about Vue hahaha :) 
It will have to be next week though, I am currently sick & coughing my lungs out, so not adapted :)
